
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile    # use special ".Dockerfile" for Go Build Setup
    container_name: salary-app
    restart: unless-stopped
    
    ports:
      - "8080:8080"
    
    env_file:
      - .env                  # Loads All Enviroment variables
    
    environment:
      PORT: "8080"
    
    depends_on:
      db:
        condition: service_healthy   # Waits until Postgres is ready
    
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:16-alpine
    container_name: salary-db
    restart: unless-stopped
    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME} # Optional: defines a default database name
   
    ports:
      - "5433:5432"          # Maps to 5433 on host â†’ avoids conflict with local Postgres
    
    volumes:
      - test-data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  test-data: